### ISSUE TITLE
Show # of Reports on Map Label

### ISSUE THREAD

**Issue by JCorrell** [ArdentMC/openFDA-Prototype#36]
On the map label, when hovering over a state, can we show # of reports along with the State Abbreviation?

**Comment by IslandWalker** [comment]
Jim, We can show number for reports from among those queried.  Is this OK?

**Comment by IslandWalker** [comment]
Done...

**Comment by JCorrell** [comment]
Yes
________________________________

**Comment by IslandWalker** [comment]
Take a look.

Eugene t. staten ii | SOFTWARE ENGINEER - Lead technology consultant | ArdentMC
Maui Software Development Center
SBA-Certified HUBZone Firm
808.757.9808 | Main
                 9831 | Extension

**Comment by JCorrell** [comment]
Looks good – I like it.

Except, I think there’s a bug.  It always shows as California with 1 report selected, even when selecting other reports.

From:  "Eugene T. Staten II"
Reply-To:  ArdentMC/openFDA-Prototype
Date:  Tuesday, June 30, 2015 at 8:49 AM
To:  ArdentMC/openFDA-Prototype
Cc:  Jim Correll
Subject:  Re: [openFDA-Prototype] Show # of Reports on Map Label (#36)

Take a look. 

Eugene t. staten ii | SOFTWARE ENGINEER - Lead technology consultant | ArdentMC 
Maui Software Development Center 
SBA-Certified HUBZone Firm 
808.757.9808 | Main 
 9831 | Extension

**Comment by IslandWalker** [comment]
Actually, it is California, selected = 1 (true).

It’s what I must do in order to have the two colors.  The queried state is the selected region (and therefore dark red) and the other states are other affected region (and therefore light red).

I am looking into a way to add the region data invisibly.

Eugene t. staten ii | SOFTWARE ENGINEER - Lead technology consultant | ArdentMC
Maui Software Development Center
SBA-Certified HUBZone Firm
808.757.9808 | Main
                 9831 | Extension

**Comment by IslandWalker** [comment]
I can make the column name RegionId???

Eugene t. staten ii | SOFTWARE ENGINEER - Lead technology consultant | ArdentMC
Maui Software Development Center
SBA-Certified HUBZone Firm
808.757.9808 | Main
                 9831 | Extension

**Comment by JCorrell** [comment]
Take we just take out that line from the popup?  Just show state name and # of records.
 
Date: Tue, 30 Jun 2015 06:20:16 -0700
